INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (1, 'MILK                                              ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (2, 'CHEESE                                            ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (3, 'EGGS                                              ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (4, 'JUICE                                             ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (5, 'CEREAL                                            ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (6, 'LEGUMES                                           ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (8, 'FISH                                              ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (9, 'INFANT CEREAL                                     ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (11, 'FORMULA                                           ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (12, 'HOMELESS JUICE                                    ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (14, 'HOMELESS TUNA                                     ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (15, 'SPECIAL MILK                                      ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (16, 'GRAINS                                            ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (17, 'INFANT FOOD                                       ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (19, 'FRUIT/VEGETABLES                                  ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (51, 'WHOLE MILK ONLY                                   ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (50, 'WHOLE MILK/YOGURT QTS                             ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (52, 'LOWFAT MILK/YOGURT QTS                            ');
INSERT INTO WIC_CAT (WIC_CAT_ID, WIC_CAT_DES) VALUES (18, 'BABY FOOD MEAT                                    ');