DROP table PROD_SCN_CD_WIC IF EXISTS ;
DROP table WIC_CAT IF EXISTS ;
DROP table WIC_SUB_CAT IF EXISTS ;
DROP table PROD_SCN_CODES IF EXISTS ;
DROP table BAT_ENVMT_CFG IF EXISTS ;
create table PROD_SCN_CD_WIC
(
	SCN_CD_ID NUMBER(17) not null,
	WIC_APL_ID NUMBER(17) not null,
	WIC_CAT_ID NUMBER not null,
	WIC_SUB_CAT_ID NUMBER not null,
	EFF_DT DATE not null,
	END_DT DATE not null,
	WIC_PROD_DES CHAR(50 char) not null,
	WIC_UNT_TXT CHAR(10 char) not null,
	WIC_PKG_SZ_QTY NUMBER(7,2) not null,
	WIC_BNFT_QTY NUMBER(7,2) not null,
	WIC_BNFT_UNT_TXT CHAR(50 char) not null,
	WIC_PRC_AMT NUMBER(7,2) not null,
	WIC_PRC_CD CHAR(2 char) not null,
	WIC_CRD_ACPT_ID CHAR(15 char) not null,
	LEB_SW CHAR(1 char) not null,
	CRE8_TS TIMESTAMP(6) not null,
	CRE8_UID CHAR(20 char) not null,
	LST_UPDT_TS TIMESTAMP(6) not null,
	LST_UPDT_UID CHAR(20 char) not null
);
create table WIC_CAT
(
	WIC_CAT_ID NUMBER not null,
	WIC_CAT_DES CHAR(50 char) not null
);
create table WIC_SUB_CAT
(
	WIC_CAT_ID NUMBER not null,
	WIC_SUB_CAT_ID NUMBER not null,
	WIC_SUB_CAT_DES CHAR(50 char) not null,
	LEB_SW CHAR(1 char) not null
);

create table PROD_SCN_CODES
(
	SCN_CD_ID NUMBER(17) not null,
	PROD_ID NUMBER,
	SCN_TYP_CD CHAR(5 char) not null,
	PRIM_SCN_CD_SW CHAR(1 char) not null,
	BNS_SCN_CD_SW CHAR(1 char) not null,
	SCN_CD_CMT CHAR(30 char),
	RETL_UNT_LN NUMBER(7,2),
	RETL_UNT_WD NUMBER(7,2),
	RETL_UNT_HT NUMBER(7,2),
	RETL_UNT_WT NUMBER(9,4),
	RETL_SELL_SZ_CD_1 CHAR(2 char),
	RETL_UNT_SELL_SZ_1 NUMBER(7,2),
	RETL_SELL_SZ_CD_2 CHAR(2 char),
	RETL_UNT_SELL_SZ_2 NUMBER(7,2),
	SAMP_PROVD_SW CHAR(1 char),
	PRPRC_OFF_PCT NUMBER(9,4),
	PROD_SUB_BRND_ID NUMBER,
	FRST_SCN_DT DATE,
	LST_SCN_DT DATE,
	CONSM_UNT_ID NUMBER,
	TAG_ITM_ID NUMBER(17),
	TAG_ITM_KEY_TYP_CD CHAR(5 char),
	TAG_SZ_DES CHAR(6 char),
	WIC_SW CHAR(1 char),
	LEB_SW CHAR(1 char),
	WIC_APL_ID NUMBER(17),
	FAM_3_CD NUMBER(5),
	FAM_4_CD NUMBER(5),
	DSD_DELD_SW CHAR(1 char),
	DSD_DEPT_OVRD_SW CHAR(1 char),
	UPC_ACTV_SW CHAR(1 char),
	SCALE_SW CHAR(1 char),
	WIC_UPDT_USR_ID CHAR(8 char),
	WIC_LST_UPDT_TS TIMESTAMP(6),
	LEB_UPDT_USR_ID CHAR(8 char),
	LEB_LST_UPDT_TS TIMESTAMP(6),
	CRE8_TS TIMESTAMP(6),
	CRE8_UID CHAR(8 char),
	LST_UPDT_TS TIMESTAMP(6),
	LST_UPDT_UID CHAR(8 char),
	LST_SYS_UPDT_ID NUMBER,
	PSE_GRAMS_WT NUMBER(9,4),
	TST_SCN_PRFMD_SW CHAR(1 char),
	DSCON_DT DATE,
	PROC_SCN_MAINT_SW CHAR(1 char)
);
CREATE TABLE BAT_ENVMT_CFG
(
  ENVMT_ID INTEGER NOT NULL ,
  CMPNT_ID VARCHAR(255) NOT NULL ,
  PROP_NM VARCHAR(255) NOT NULL ,
  PROP_VAL_TXT VARCHAR(1024) ,
  PROP_VAL_ENCD_SW VARCHAR(1) ,
  PROP_VAL_ENC_CD VARCHAR(5)
)